import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import { PermanentMarker, ZenKaku, ZillaSlab } from '../styles/fonts';
import { css } from '../../styled-system/css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${ZenKaku.variable} ${ZillaSlab.variable} ${PermanentMarker.variable}`}
    >
      <body
        className={css({
          bg: 'slate.900',
          color: 'slate.50'
        })}
      >
        {children}
      </body>
    </html>
  );
}
